<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductionFieldsSeeder extends Seeder
{
    public function run()
    {
        $fields = [
            [
                "id" => 295,
                "entity_type" => "new_yacht",
                "group" => null,
                "field_key" => "brand",
                "field_type" => "brand",
                "label" => "Brand",
                "is_required" => true,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 0,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 296,
                "entity_type" => "new_yacht",
                "group" => null,
                "field_key" => "model",
                "field_type" => "model",
                "label" => "Model",
                "is_required" => true,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 1,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 297,
                "entity_type" => "new_yacht",
                "group" => "Content & Specifications ",
                "field_key" => "sub_title",
                "field_type" => "richtext",
                "label" => "Sub Title",
                "is_required" => false,
                "is_multilingual" => true,
                "sync_as_taxonomy" => false,
                "order" => 2,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 298,
                "entity_type" => "new_yacht",
                "group" => "Content & Specifications ",
                "field_key" => "specifications",
                "field_type" => "richtext",
                "label" => "Specifications (tehnical data)",
                "is_required" => false,
                "is_multilingual" => true,
                "sync_as_taxonomy" => false,
                "order" => 3,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 299,
                "entity_type" => "new_yacht",
                "group" => "Content & Specifications ",
                "field_key" => "full_description",
                "field_type" => "richtext",
                "label" => "Full Description",
                "is_required" => false,
                "is_multilingual" => true,
                "sync_as_taxonomy" => false,
                "order" => 4,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 300,
                "entity_type" => "new_yacht",
                "group" => "Filters",
                "field_key" => "type",
                "field_type" => "select",
                "label" => "Type",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 5,
                "options" => '[{"value":"yacht","label":"Yacht"},{"value":"daly_crouser","label":"Daily Crouser"},{"value":"sport_boat","label":"Sport Boat"},{"value":"sailling_boat","label":"Sailling boat"}]',
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 301,
                "entity_type" => "new_yacht",
                "group" => "Filters",
                "field_key" => "length",
                "field_type" => "number",
                "label" => "Length",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 6,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 302,
                "entity_type" => "new_yacht",
                "group" => "Filters",
                "field_key" => "engine_type",
                "field_type" => "checkbox",
                "label" => "Engine type",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 7,
                "options" => '[{"value":"petrol","label":"Petrol"},{"value":"disel","label":"Diesel"},{"value":"hybrid","label":"Hybrid"},{"value":"electric","label":"Electric"}]',
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 303,
                "entity_type" => "new_yacht",
                "group" => "Filters",
                "field_key" => "engine_location",
                "field_type" => "checkbox",
                "label" => "Engine location",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 8,
                "options" => '[{"value":"internal","label":"Internal"},{"value":"external","label":"External"}]',
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 304,
                "entity_type" => "new_yacht",
                "group" => "Filters",
                "field_key" => "no_cabins",
                "field_type" => "select",
                "label" => "Number of cabins",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 9,
                "options" => '[{"value":"0","label":"0"},{"value":"1","label":"1"},{"value":"2","label":"2"},{"value":"3","label":"3"},{"value":"4","label":"4 or more"}]',
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 305,
                "entity_type" => "new_yacht",
                "group" => "Filters",
                "field_key" => "number_of_bathrooms",
                "field_type" => "select",
                "label" => "Number of Bathrooms",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 10,
                "options" => '[{"value":"0","label":"0"},{"value":"1","label":"1"},{"value":"2","label":"2"},{"value":"3","label":"3"},{"value":"4","label":"4 or more"}]',
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 306,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "cover_image",
                "field_type" => "image",
                "label" => "Cover Image",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 11,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 307,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "grid_image",
                "field_type" => "image",
                "label" => "Grid Image",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 12,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 308,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "grid_image_hover",
                "field_type" => "image",
                "label" => "Grid image hover",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 13,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 309,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "pdf_brochure",
                "field_type" => "file",
                "label" => "PDF Brochure",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 14,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 310,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "video_url",
                "field_type" => "repeater",
                "label" => "Video URL (ex. youtube)",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 15,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 311,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "gallery_exterior",
                "field_type" => "gallery",
                "label" => "Gallery Exterior",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 16,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 312,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "gallery_interior",
                "field_type" => "gallery",
                "label" => "Gallery Interior",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 17,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 313,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "gallery_cockpit",
                "field_type" => "gallery",
                "label" => "Gallery Cockpit",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 18,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ],
            [
                "id" => 314,
                "entity_type" => "new_yacht",
                "group" => "Media",
                "field_key" => "gallery_layout",
                "field_type" => "gallery",
                "label" => "Gallery layout(s)",
                "is_required" => false,
                "is_multilingual" => false,
                "sync_as_taxonomy" => false,
                "order" => 19,
                "options" => null,
                "validation_rules" => "[]",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now()
            ]
        ];

        // Clean existing new_yacht fields to prevent duplicates
        DB::table('form_field_configurations')->where('entity_type', 'new_yacht')->delete();

        // Insert new fields
        DB::table('form_field_configurations')->insert($fields);

        // Reset auto increment (optional, specific to DB driver but generally safe to ignore for this temp seeder)
    }
}
